<?xml version="1.0" standalone="yes"?>

<?program_dtd version="1"?>

<!DOCTYPE PROGRAM [

<!ELEMENT PROGRAM (DESCRIPTION?,
                   INFO_SOURCE?,
                   PROCESSOR?,
                   COMPILER?,
                   DATATYPES?,
                   MEMORY_MAP?,
                   REGISTER_VALUES?,
                   CODE?,
                   DATA?,
                   EQUATES?,
                   COMMENTS?,
                   PROPERTIES?,
                   BOOKMARKS?,
                   PROGRAM_TREES?,
                   PROGRAM_ENTRY_POINTS?,
                   RELOCATION_TABLE?,
                   SYMBOL_TABLE?,
                   FUNCTIONS?,
                   MARKUP?,
                   EXT_LIBRARY_TABLE?)>
  <!ATTLIST PROGRAM NAME       CDATA #REQUIRED>
  <!ATTLIST PROGRAM EXE_PATH   CDATA #IMPLIED>
  <!ATTLIST PROGRAM EXE_FORMAT CDATA #IMPLIED>
  <!ATTLIST PROGRAM IMAGE_BASE CDATA #IMPLIED>

<!ELEMENT DISPLAY_SETTINGS EMPTY>
  <!ATTLIST DISPLAY_SETTINGS FORMAT           (hex | decimal | octal | binary | char) #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SIGNED           (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ZERO_PAD         (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ENDIAN           (big | little)                          #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SHOW_TERMINATOR  (y | n)                                 #IMPLIED>

<!ELEMENT DESCRIPTION    (#PCDATA)>
<!ELEMENT REGULAR_CMT    (#PCDATA)>
<!ELEMENT REPEATABLE_CMT (#PCDATA)>
<!ELEMENT TYPEINFO_CMT   (#PCDATA)>

<!ELEMENT INFO_SOURCE EMPTY>
  <!ATTLIST INFO_SOURCE USER      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TOOL      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE FILE      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TIMESTAMP CDATA #IMPLIED>

<!ELEMENT PROCESSOR EMPTY>
  <!ATTLIST PROCESSOR NAME              CDATA          #REQUIRED>
  <!ATTLIST PROCESSOR FAMILY            CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR LANGUAGE_PROVIDER CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR ENDIAN            (big | little) #IMPLIED>
  <!ATTLIST PROCESSOR ADDRESS_MODEL     CDATA          #IMPLIED>

<!-- TODO: expand compiler tag -->
<!ELEMENT COMPILER EMPTY>
  <!ATTLIST COMPILER NAME CDATA #REQUIRED>

<!ELEMENT MEMORY_MAP (MEMORY_SECTION*)>

<!ELEMENT MEMORY_SECTION ((MEMORY_CONTENTS*) | (BIT_MAPPED?))>
  <!ATTLIST MEMORY_SECTION NAME         CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION START_ADDR   CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION LENGTH       CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION PERMISSIONS  (r | w | x | rw | rx | wx | rwx)  #IMPLIED>
  <!ATTLIST MEMORY_SECTION VOLATILE     (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION COMMENT      CDATA                             #IMPLIED>

<!ELEMENT MEMORY_CONTENTS EMPTY>
  <!ATTLIST MEMORY_CONTENTS START_ADDR   CDATA  #IMPLIED>
  <!ATTLIST MEMORY_CONTENTS FILE_NAME    CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS FILE_OFFSET  CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS LENGTH       CDATA  #IMPLIED>

<!ELEMENT BIT_MAPPED EMPTY>
  <!ATTLIST BIT_MAPPED SOURCE_ADDRESS  CDATA  #REQUIRED>

<!ELEMENT REGISTER_VALUES (REGISTER_VALUE_RANGE*)>

<!ELEMENT REGISTER_VALUE_RANGE EMPTY>
  <!ATTLIST REGISTER_VALUE_RANGE REGISTER      CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE VALUE         CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE START_ADDRESS CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE LENGTH        CDATA #REQUIRED>

<!ELEMENT CODE (CODE_BLOCK*)>

<!ELEMENT CODE_BLOCK EMPTY>
  <!ATTLIST CODE_BLOCK  START  CDATA  #REQUIRED>
  <!ATTLIST CODE_BLOCK  END    CDATA  #REQUIRED>

<!ELEMENT DATA (DEFINED_DATA*)>

<!ELEMENT DEFINED_DATA (TYPEINFO_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST DEFINED_DATA ADDRESS             CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST DEFINED_DATA SIZE                CDATA  #IMPLIED>

<!ELEMENT EQUATES (EQUATE_GROUP*)>

<!ELEMENT EQUATE_GROUP (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, (EQUATE | BIT_MASK)*)>
  <!ATTLIST EQUATE_GROUP NAME       CDATA       #IMPLIED>
  <!ATTLIST EQUATE_GROUP BIT_FIELD  (yes | no)  #IMPLIED>

<!ELEMENT EQUATE (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST EQUATE NAME     CDATA  #REQUIRED>
  <!ATTLIST EQUATE VALUE    CDATA  #REQUIRED>
  <!ATTLIST EQUATE BIT_MASK CDATA  #IMPLIED>

<!ELEMENT BIT_MASK (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST BIT_MASK NAME   CDATA  #REQUIRED>
  <!ATTLIST BIT_MASK VALUE  CDATA  #REQUIRED>

<!ELEMENT COMMENTS (COMMENT*)>

<!ELEMENT COMMENT (#PCDATA)>
  <!ATTLIST COMMENT ADDRESS  CDATA                                            #REQUIRED>
  <!ATTLIST COMMENT TYPE     (end-of-line | repeatable | pre | post | plate)  #REQUIRED>

<!ELEMENT PROPERTIES (PROPERTY*)>

<!ELEMENT PROPERTY EMPTY>
  <!ATTLIST PROPERTY NAME     CDATA                                                #REQUIRED>
  <!ATTLIST PROPERTY ADDRESS  CDATA                                                #IMPLIED>
  <!ATTLIST PROPERTY TYPE     (string | long | int | double | void | bool | date)  #IMPLIED>
  <!ATTLIST PROPERTY VALUE    CDATA                                                #IMPLIED>

<!ELEMENT BOOKMARKS (BOOKMARK*)>

<!ELEMENT BOOKMARK EMPTY>
  <!ATTLIST BOOKMARK ADDRESS     CDATA  #REQUIRED>
  <!ATTLIST BOOKMARK TYPE        CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK CATEGORY    CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK DESCRIPTION CDATA  #IMPLIED>

<!ELEMENT PROGRAM_TREES (TREE*)>

<!ELEMENT TREE ((FOLDER | FRAGMENT)*)>
  <!ATTLIST TREE NAME CDATA #REQUIRED>

<!ELEMENT FOLDER ((FOLDER | FRAGMENT)*)>
  <!ATTLIST FOLDER NAME CDATA #REQUIRED>

<!ELEMENT FRAGMENT (ADDRESS_RANGE)*>
  <!ATTLIST FRAGMENT NAME CDATA #REQUIRED>

<!ELEMENT ADDRESS_RANGE EMPTY>
  <!ATTLIST ADDRESS_RANGE START  CDATA  #REQUIRED>
  <!ATTLIST ADDRESS_RANGE END    CDATA  #REQUIRED>

<!ELEMENT PROGRAM_ENTRY_POINTS (PROGRAM_ENTRY_POINT*)>

<!ELEMENT PROGRAM_ENTRY_POINT EMPTY>
  <!ATTLIST PROGRAM_ENTRY_POINT  ADDRESS  CDATA  #REQUIRED>

<!ELEMENT RELOCATION_TABLE (RELOCATION*)>

<!ELEMENT RELOCATION EMPTY>
  <!ATTLIST RELOCATION ADDRESS  CDATA  #REQUIRED>
  <!ATTLIST RELOCATION TYPE     CDATA  #REQUIRED>
  <!ATTLIST RELOCATION VALUE    CDATA  #REQUIRED>
  <!ATTLIST RELOCATION BYTES    CDATA  #IMPLIED>

<!ELEMENT SYMBOL_TABLE (SYMBOL*)>

<!ELEMENT SYMBOL EMPTY>
  <!ATTLIST SYMBOL ADDRESS   		CDATA            					 #REQUIRED>
  <!ATTLIST SYMBOL NAME      		CDATA             					 #REQUIRED>
  <!ATTLIST SYMBOL NAMESPACE 		CDATA             					 #IMPLIED>
  <!ATTLIST SYMBOL TYPE      		(global | local)  					 #IMPLIED>
  <!ATTLIST SYMBOL SOURCE_TYPE      (USER_DEFINED | IMPORTED | ANALYSIS) #IMPLIED>
  <!ATTLIST SYMBOL PRIMARY   		(y | n)           					 #IMPLIED>
  <!ATTLIST SYMBOL MANGLED   		CDATA             					 #IMPLIED>

<!ELEMENT FUNCTIONS (FUNCTION*)>

<!ELEMENT FUNCTION (RETURN_TYPE?, ADDRESS_RANGE*, REGULAR_CMT?, REPEATABLE_CMT?, TYPEINFO_CMT?, STACK_FRAME?, REGISTER_VAR*)>
  <!ATTLIST FUNCTION ENTRY_POINT       CDATA   #REQUIRED>
  <!ATTLIST FUNCTION NAME              CDATA   #IMPLIED>
  <!-- TODO: create xml attrs for each known attribute type -->
  <!ATTLIST FUNCTION LIBRARY_FUNCTION  (y | n) #IMPLIED>

<!ELEMENT RETURN_TYPE EMPTY>
  <!ATTLIST RETURN_TYPE DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST RETURN_TYPE DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST RETURN_TYPE SIZE                CDATA  #IMPLIED>

<!ELEMENT STACK_FRAME (STACK_VAR*)>
  <!ATTLIST STACK_FRAME LOCAL_VAR_SIZE         CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME PARAM_OFFSET           CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME REGISTER_SAVE_SIZE     CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME RETURN_ADDR_SIZE       CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME BYTES_PURGED           CDATA    #IMPLIED>

<!ELEMENT STACK_VAR (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST STACK_VAR STACK_PTR_OFFSET    CDATA  #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_VAR FRAME_PTR_OFFSET    CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR NAME                CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST STACK_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR SIZE                CDATA  #IMPLIED>

<!ELEMENT REGISTER_VAR (REGULAR_CMT?)>
  <!ATTLIST REGISTER_VAR NAME                CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR REGISTER            CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR DATATYPE            CDATA  #IMPLIED>
  <!ATTLIST REGISTER_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT MARKUP (MEMORY_REFERENCE      |
                  STACK_REFERENCE       |
                  EXT_LIBRARY_REFERENCE |
                  EQUATE_REFERENCE      |
                  MANUAL_OPERAND        |
                  MANUAL_INSTRUCTION)*>

<!-- An OPERAND_INDEX is omitted for a mnemonic reference    -->
<!-- The first operand is identified with OPERAND_INDEX=0 -->
<!ELEMENT MEMORY_REFERENCE EMPTY>
  <!ATTLIST MEMORY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE TO_ADDRESS     CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE BASE_ADDRESS   CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE PRIMARY        (y | n)  #IMPLIED>

<!ELEMENT STACK_REFERENCE EMPTY>
  <!ATTLIST STACK_REFERENCE ADDRESS          CDATA    #REQUIRED>
  <!ATTLIST STACK_REFERENCE OPERAND_INDEX    CDATA    #IMPLIED>
  <!ATTLIST STACK_REFERENCE USER_DEFINED     (y | n)  #IMPLIED>
  <!ATTLIST STACK_REFERENCE STACK_PTR_OFFSET CDATA    #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_REFERENCE FRAME_PTR_OFFSET CDATA    #IMPLIED>

<!ELEMENT EXT_LIBRARY_REFERENCE EMPTY>
  <!ATTLIST EXT_LIBRARY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_PROG_NAME  CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_LABEL      CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ORDINAL    CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ADDR       CDATA    #IMPLIED>

<!ELEMENT EQUATE_REFERENCE EMPTY>
  <!ATTLIST EQUATE_REFERENCE ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE OPERAND_INDEX  CDATA  #IMPLIED>
  <!ATTLIST EQUATE_REFERENCE NAME           CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE VALUE          CDATA  #IMPLIED>

<!ELEMENT MANUAL_OPERAND (#PCDATA)>
  <!ATTLIST MANUAL_OPERAND ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST MANUAL_OPERAND OPERAND_INDEX  CDATA  #REQUIRED>

<!ELEMENT MANUAL_INSTRUCTION (#PCDATA)>
  <!ATTLIST MANUAL_INSTRUCTION ADDRESS CDATA #REQUIRED>

<!ELEMENT EXT_LIBRARY_TABLE (EXT_LIBRARY*)>

<!ELEMENT EXT_LIBRARY EMPTY>
  <!ATTLIST EXT_LIBRARY NAME  CDATA  #REQUIRED>
  <!ATTLIST EXT_LIBRARY PATH  CDATA  #IMPLIED>

<!-- ************************************************************* -->
<!--                                                               -->
<!--                Data DTD                                       -->
<!--                                                               -->
<!-- ************************************************************* -->

<!ELEMENT DATATYPES (STRUCTURE | UNION | FUNCTION_DEF | ENUM | TYPE_DEF)*>

<!ELEMENT MEMBER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST MEMBER OFFSET              CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST MEMBER NAME                CDATA  #IMPLIED>
  <!ATTLIST MEMBER SIZE                CDATA  #IMPLIED>

<!ELEMENT STRUCTURE (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST STRUCTURE NAME             CDATA   #REQUIRED>
  <!ATTLIST STRUCTURE NAMESPACE        CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE SIZE             CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE VARIABLE_LENGTH  (y | n) #IMPLIED>

<!ELEMENT UNION (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST UNION NAME       CDATA  #REQUIRED>
  <!ATTLIST UNION NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST UNION SIZE       CDATA  #IMPLIED>

<!ELEMENT FUNCTION_DEF (REGULAR_CMT?, REPEATABLE_CMT?, RETURN_TYPE?, PARAMETER*)>
  <!ATTLIST FUNCTION_DEF NAME       CDATA  #REQUIRED>
  <!ATTLIST FUNCTION_DEF NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT PARAMETER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST PARAMETER ORDINAL             CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST PARAMETER NAME                CDATA  #IMPLIED>
  <!ATTLIST PARAMETER SIZE                CDATA  #IMPLIED>

<!ELEMENT TYPE_DEF (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST TYPE_DEF NAME                CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF NAMESPACE           CDATA #IMPLIED>
  <!ATTLIST TYPE_DEF DATATYPE            CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF DATATYPE_NAMESPACE  CDATA #IMPLIED>

<!ELEMENT ENUM (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, ENUM_ENTRY*)>
  <!ATTLIST ENUM NAME       CDATA  #REQUIRED>
  <!ATTLIST ENUM NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST ENUM SIZE       CDATA  #IMPLIED>

<!ELEMENT ENUM_ENTRY (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST ENUM_ENTRY NAME   CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY VALUE  CDATA  #REQUIRED>

]>
<PROGRAM NAME="heartbleeder_x64.exe" EXE_PATH="/tmp/mozilla_fouque0/heartbleeder_x64.exe" EXE_FORMAT="Portable Executable (PE)" IMAGE_BASE="00400000">
    <INFO_SOURCE USER="fouque" TOOL="Ghidra 9.1.2" TIMESTAMP="Wed Jul 08 14:34:10 CEST 2020" />
    <PROCESSOR NAME="x86" LANGUAGE_PROVIDER="x86:LE:64:default:windows" ENDIAN="little" />
    <DATATYPES>
        <STRUCTURE NAME="IMAGE_DATA_DIRECTORY" NAMESPACE="/PE" SIZE="0x8">
            <MEMBER OFFSET="0x0" DATATYPE="ImageBaseOffset32" DATATYPE_NAMESPACE="/" NAME="VirtualAddress" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="Size" SIZE="0x4" />
        </STRUCTURE>
        <STRUCTURE NAME="IMAGE_DOS_HEADER" NAMESPACE="/DOS" SIZE="0x80">
            <MEMBER OFFSET="0x0" DATATYPE="char[2]" DATATYPE_NAMESPACE="/" NAME="e_magic" SIZE="0x2">
                <REGULAR_CMT>Magic number</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x2" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_cblp" SIZE="0x2">
                <REGULAR_CMT>Bytes of last page</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x4" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_cp" SIZE="0x2">
                <REGULAR_CMT>Pages in file</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x6" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_crlc" SIZE="0x2">
                <REGULAR_CMT>Relocations</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x8" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_cparhdr" SIZE="0x2">
                <REGULAR_CMT>Size of header in paragraphs</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0xa" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_minalloc" SIZE="0x2">
                <REGULAR_CMT>Minimum extra paragraphs needed</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0xc" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_maxalloc" SIZE="0x2">
                <REGULAR_CMT>Maximum extra paragraphs needed</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0xe" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_ss" SIZE="0x2">
                <REGULAR_CMT>Initial (relative) SS value</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x10" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_sp" SIZE="0x2">
                <REGULAR_CMT>Initial SP value</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x12" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_csum" SIZE="0x2">
                <REGULAR_CMT>Checksum</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x14" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_ip" SIZE="0x2">
                <REGULAR_CMT>Initial IP value</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x16" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_cs" SIZE="0x2">
                <REGULAR_CMT>Initial (relative) CS value</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x18" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_lfarlc" SIZE="0x2">
                <REGULAR_CMT>File address of relocation table</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x1a" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_ovno" SIZE="0x2">
                <REGULAR_CMT>Overlay number</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x1c" DATATYPE="word[4]" DATATYPE_NAMESPACE="/" NAME="e_res[4]" SIZE="0x8">
                <REGULAR_CMT>Reserved words</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x24" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_oemid" SIZE="0x2">
                <REGULAR_CMT>OEM identifier (for e_oeminfo)</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x26" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_oeminfo" SIZE="0x2">
                <REGULAR_CMT>OEM information; e_oemid specific</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x28" DATATYPE="word[10]" DATATYPE_NAMESPACE="/" NAME="e_res2[10]" SIZE="0x14">
                <REGULAR_CMT>Reserved words</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x3c" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="e_lfanew" SIZE="0x4">
                <REGULAR_CMT>File address of new exe header</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x40" DATATYPE="byte[64]" DATATYPE_NAMESPACE="/" NAME="e_program" SIZE="0x40">
                <REGULAR_CMT>Actual DOS program</REGULAR_CMT>
            </MEMBER>
        </STRUCTURE>
        <STRUCTURE NAME="IMAGE_FILE_HEADER" NAMESPACE="/PE" SIZE="0x14">
            <MEMBER OFFSET="0x0" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="Machine" SIZE="0x2">
                <REGULAR_CMT>34404</REGULAR_CMT>
            </MEMBER>
            <MEMBER OFFSET="0x2" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="NumberOfSections" SIZE="0x2" />
            <MEMBER OFFSET="0x4" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="TimeDateStamp" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="PointerToSymbolTable" SIZE="0x4" />
            <MEMBER OFFSET="0xc" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="NumberOfSymbols" SIZE="0x4" />
            <MEMBER OFFSET="0x10" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="SizeOfOptionalHeader" SIZE="0x2" />
            <MEMBER OFFSET="0x12" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="Characteristics" SIZE="0x2" />
        </STRUCTURE>
        <STRUCTURE NAME="IMAGE_NT_HEADERS32" NAMESPACE="/PE" SIZE="0x108">
            <MEMBER OFFSET="0x0" DATATYPE="char[4]" DATATYPE_NAMESPACE="/" NAME="Signature" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="IMAGE_FILE_HEADER" DATATYPE_NAMESPACE="/PE" NAME="FileHeader" SIZE="0x14" />
            <MEMBER OFFSET="0x18" DATATYPE="IMAGE_OPTIONAL_HEADER64" DATATYPE_NAMESPACE="/PE" NAME="OptionalHeader" SIZE="0xf0" />
        </STRUCTURE>
        <STRUCTURE NAME="IMAGE_OPTIONAL_HEADER64" NAMESPACE="/PE" SIZE="0xf0">
            <MEMBER OFFSET="0x0" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="Magic" SIZE="0x2" />
            <MEMBER OFFSET="0x2" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="MajorLinkerVersion" SIZE="0x1" />
            <MEMBER OFFSET="0x3" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="MinorLinkerVersion" SIZE="0x1" />
            <MEMBER OFFSET="0x4" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="SizeOfCode" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="SizeOfInitializedData" SIZE="0x4" />
            <MEMBER OFFSET="0xc" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="SizeOfUninitializedData" SIZE="0x4" />
            <MEMBER OFFSET="0x10" DATATYPE="ImageBaseOffset32" DATATYPE_NAMESPACE="/" NAME="AddressOfEntryPoint" SIZE="0x4" />
            <MEMBER OFFSET="0x14" DATATYPE="ImageBaseOffset32" DATATYPE_NAMESPACE="/" NAME="BaseOfCode" SIZE="0x4" />
            <MEMBER OFFSET="0x18" DATATYPE="pointer64" DATATYPE_NAMESPACE="/" NAME="ImageBase" SIZE="0x8" />
            <MEMBER OFFSET="0x20" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="SectionAlignment" SIZE="0x4" />
            <MEMBER OFFSET="0x24" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="FileAlignment" SIZE="0x4" />
            <MEMBER OFFSET="0x28" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="MajorOperatingSystemVersion" SIZE="0x2" />
            <MEMBER OFFSET="0x2a" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="MinorOperatingSystemVersion" SIZE="0x2" />
            <MEMBER OFFSET="0x2c" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="MajorImageVersion" SIZE="0x2" />
            <MEMBER OFFSET="0x2e" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="MinorImageVersion" SIZE="0x2" />
            <MEMBER OFFSET="0x30" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="MajorSubsystemVersion" SIZE="0x2" />
            <MEMBER OFFSET="0x32" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="MinorSubsystemVersion" SIZE="0x2" />
            <MEMBER OFFSET="0x34" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="Win32VersionValue" SIZE="0x4" />
            <MEMBER OFFSET="0x38" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="SizeOfImage" SIZE="0x4" />
            <MEMBER OFFSET="0x3c" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="SizeOfHeaders" SIZE="0x4" />
            <MEMBER OFFSET="0x40" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="CheckSum" SIZE="0x4" />
            <MEMBER OFFSET="0x44" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="Subsystem" SIZE="0x2" />
            <MEMBER OFFSET="0x46" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="DllCharacteristics" SIZE="0x2" />
            <MEMBER OFFSET="0x48" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="SizeOfStackReserve" SIZE="0x8" />
            <MEMBER OFFSET="0x50" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="SizeOfStackCommit" SIZE="0x8" />
            <MEMBER OFFSET="0x58" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="SizeOfHeapReserve" SIZE="0x8" />
            <MEMBER OFFSET="0x60" DATATYPE="qword" DATATYPE_NAMESPACE="/" NAME="SizeOfHeapCommit" SIZE="0x8" />
            <MEMBER OFFSET="0x68" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="LoaderFlags" SIZE="0x4" />
            <MEMBER OFFSET="0x6c" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="NumberOfRvaAndSizes" SIZE="0x4" />
            <MEMBER OFFSET="0x70" DATATYPE="IMAGE_DATA_DIRECTORY[16]" DATATYPE_NAMESPACE="/PE" NAME="DataDirectory" SIZE="0x80" />
        </STRUCTURE>
        <STRUCTURE NAME="IMAGE_SECTION_HEADER" NAMESPACE="/PE" SIZE="0x28">
            <MEMBER OFFSET="0x0" DATATYPE="char[8]" DATATYPE_NAMESPACE="/" NAME="Name" SIZE="0x8" />
            <MEMBER OFFSET="0x8" DATATYPE="Misc" DATATYPE_NAMESPACE="/PE" NAME="Misc" SIZE="0x4" />
            <MEMBER OFFSET="0xc" DATATYPE="ImageBaseOffset32" DATATYPE_NAMESPACE="/" NAME="VirtualAddress" SIZE="0x4" />
            <MEMBER OFFSET="0x10" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="SizeOfRawData" SIZE="0x4" />
            <MEMBER OFFSET="0x14" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="PointerToRawData" SIZE="0x4" />
            <MEMBER OFFSET="0x18" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="PointerToRelocations" SIZE="0x4" />
            <MEMBER OFFSET="0x1c" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="PointerToLinenumbers" SIZE="0x4" />
            <MEMBER OFFSET="0x20" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="NumberOfRelocations" SIZE="0x2" />
            <MEMBER OFFSET="0x22" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="NumberOfLinenumbers" SIZE="0x2" />
            <MEMBER OFFSET="0x24" DATATYPE="SectionFlags" DATATYPE_NAMESPACE="/PE" NAME="Characteristics" SIZE="0x4" />
        </STRUCTURE>
        <UNION NAME="Misc" NAMESPACE="/PE" SIZE="0x4">
            <MEMBER OFFSET="0x0" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="PhysicalAddress" SIZE="0x4" />
            <MEMBER OFFSET="0x0" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="VirtualSize" SIZE="0x4" />
        </UNION>
        <ENUM NAME="SectionFlags" NAMESPACE="/PE" SIZE="0x4">
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_1024BYTES" VALUE="0xb00000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_128BYTES" VALUE="0x800000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_16BYTES" VALUE="0x500000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_1BYTES" VALUE="0x100000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_2048BYTES" VALUE="0xc00000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_256BYTES" VALUE="0x900000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_2BYTES" VALUE="0x200000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_32BYTES" VALUE="0x600000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_4096BYTES" VALUE="0xd00000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_4BYTES" VALUE="0x300000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_512BYTES" VALUE="0xa00000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_64BYTES" VALUE="0x700000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_8192BYTES" VALUE="0xe00000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_ALIGN_8BYTES" VALUE="0x400000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_CNT_CODE" VALUE="0x20" />
            <ENUM_ENTRY NAME="IMAGE_SCN_CNT_INITIALIZED_DATA" VALUE="0x40" />
            <ENUM_ENTRY NAME="IMAGE_SCN_CNT_UNINITIALIZED_DATA" VALUE="0x80" />
            <ENUM_ENTRY NAME="IMAGE_SCN_GPREL" VALUE="0x8000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_LNK_COMDAT" VALUE="0x1000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_LNK_INFO" VALUE="0x200" />
            <ENUM_ENTRY NAME="IMAGE_SCN_LNK_NRELOC_OVFL" VALUE="0x1000000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_LNK_OTHER" VALUE="0x100" />
            <ENUM_ENTRY NAME="IMAGE_SCN_LNK_REMOVE" VALUE="0x800" />
            <ENUM_ENTRY NAME="IMAGE_SCN_MEM_16BIT" VALUE="0x20000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_MEM_DISCARDABLE" VALUE="0x2000000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_MEM_EXECUTE" VALUE="0x20000000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_MEM_LOCKED" VALUE="0x40000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_MEM_NOT_CACHED" VALUE="0x4000000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_MEM_NOT_PAGED" VALUE="0x8000000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_MEM_PRELOAD" VALUE="0x80000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_MEM_PURGEABLE" VALUE="0x20000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_MEM_READ" VALUE="0x40000000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_MEM_SHARED" VALUE="0x10000000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_MEM_WRITE" VALUE="0x80000000" />
            <ENUM_ENTRY NAME="IMAGE_SCN_RESERVED_0001" VALUE="0x10" />
            <ENUM_ENTRY NAME="IMAGE_SCN_RESERVED_0040" VALUE="0x400" />
            <ENUM_ENTRY NAME="IMAGE_SCN_TYPE_NO_PAD" VALUE="0x8" />
        </ENUM>
    </DATATYPES>
    <MEMORY_MAP>
        <MEMORY_SECTION NAME="Headers" START_ADDR="00400000" LENGTH="0x600" PERMISSIONS="r" COMMENT="">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_x64.bytes" FILE_OFFSET="0x0" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME=".text" START_ADDR="00401000" LENGTH="0x522a00" PERMISSIONS="rx" COMMENT="">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_x64.bytes" FILE_OFFSET="0x600" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME=".data" START_ADDR="00924000" LENGTH="0x1fc00" PERMISSIONS="rw" COMMENT="">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_x64.bytes" FILE_OFFSET="0x523000" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME=".data" START_ADDR="00943c00" LENGTH="0x205c8" PERMISSIONS="rw" COMMENT="" />
        <MEMORY_SECTION NAME="/4" START_ADDR="00965000" LENGTH="0x200" PERMISSIONS="r" COMMENT="">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_x64.bytes" FILE_OFFSET="0x542c00" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="/18" START_ADDR="00966000" LENGTH="0x31000" PERMISSIONS="r" COMMENT="">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_x64.bytes" FILE_OFFSET="0x542e00" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="/30" START_ADDR="00997000" LENGTH="0x3c800" PERMISSIONS="r" COMMENT="">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_x64.bytes" FILE_OFFSET="0x57ae00" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="/43" START_ADDR="009d4000" LENGTH="0xfb000" PERMISSIONS="r" COMMENT="">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_x64.bytes" FILE_OFFSET="0x5b7600" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="/55" START_ADDR="00acf000" LENGTH="0x44400" PERMISSIONS="r" COMMENT="">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_x64.bytes" FILE_OFFSET="0x6b7600" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="/71" START_ADDR="00b14000" LENGTH="0x1a000" PERMISSIONS="r" COMMENT="">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_x64.bytes" FILE_OFFSET="0x6fba00" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="/87" START_ADDR="00b2e000" LENGTH="0x200" PERMISSIONS="r" COMMENT="">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_x64.bytes" FILE_OFFSET="0x715c00" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME=".idata" START_ADDR="00b2f000" LENGTH="0x600" PERMISSIONS="rw" COMMENT="">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_x64.bytes" FILE_OFFSET="0x715e00" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME=".symtab" START_ADDR="00b30000" LENGTH="0x62600" PERMISSIONS="r" COMMENT="">