<?xml version="1.0" standalone="yes"?>

<?program_dtd version="1"?>

<!DOCTYPE PROGRAM [

<!ELEMENT PROGRAM (DESCRIPTION?,
                   INFO_SOURCE?,
                   PROCESSOR?,
                   COMPILER?,
                   DATATYPES?,
                   MEMORY_MAP?,
                   REGISTER_VALUES?,
                   CODE?,
                   DATA?,
                   EQUATES?,
                   COMMENTS?,
                   PROPERTIES?,
                   BOOKMARKS?,
                   PROGRAM_TREES?,
                   PROGRAM_ENTRY_POINTS?,
                   RELOCATION_TABLE?,
                   SYMBOL_TABLE?,
                   FUNCTIONS?,
                   MARKUP?,
                   EXT_LIBRARY_TABLE?)>
  <!ATTLIST PROGRAM NAME       CDATA #REQUIRED>
  <!ATTLIST PROGRAM EXE_PATH   CDATA #IMPLIED>
  <!ATTLIST PROGRAM EXE_FORMAT CDATA #IMPLIED>
  <!ATTLIST PROGRAM IMAGE_BASE CDATA #IMPLIED>

<!ELEMENT DISPLAY_SETTINGS EMPTY>
  <!ATTLIST DISPLAY_SETTINGS FORMAT           (hex | decimal | octal | binary | char) #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SIGNED           (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ZERO_PAD         (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ENDIAN           (big | little)                          #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SHOW_TERMINATOR  (y | n)                                 #IMPLIED>

<!ELEMENT DESCRIPTION    (#PCDATA)>
<!ELEMENT REGULAR_CMT    (#PCDATA)>
<!ELEMENT REPEATABLE_CMT (#PCDATA)>
<!ELEMENT TYPEINFO_CMT   (#PCDATA)>

<!ELEMENT INFO_SOURCE EMPTY>
  <!ATTLIST INFO_SOURCE USER      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TOOL      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE FILE      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TIMESTAMP CDATA #IMPLIED>

<!ELEMENT PROCESSOR EMPTY>
  <!ATTLIST PROCESSOR NAME              CDATA          #REQUIRED>
  <!ATTLIST PROCESSOR FAMILY            CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR LANGUAGE_PROVIDER CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR ENDIAN            (big | little) #IMPLIED>
  <!ATTLIST PROCESSOR ADDRESS_MODEL     CDATA          #IMPLIED>

<!-- TODO: expand compiler tag -->
<!ELEMENT COMPILER EMPTY>
  <!ATTLIST COMPILER NAME CDATA #REQUIRED>

<!ELEMENT MEMORY_MAP (MEMORY_SECTION*)>

<!ELEMENT MEMORY_SECTION ((MEMORY_CONTENTS*) | (BIT_MAPPED?))>
  <!ATTLIST MEMORY_SECTION NAME         CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION START_ADDR   CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION LENGTH       CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION PERMISSIONS  (r | w | x | rw | rx | wx | rwx)  #IMPLIED>
  <!ATTLIST MEMORY_SECTION VOLATILE     (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION COMMENT      CDATA                             #IMPLIED>

<!ELEMENT MEMORY_CONTENTS EMPTY>
  <!ATTLIST MEMORY_CONTENTS START_ADDR   CDATA  #IMPLIED>
  <!ATTLIST MEMORY_CONTENTS FILE_NAME    CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS FILE_OFFSET  CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS LENGTH       CDATA  #IMPLIED>

<!ELEMENT BIT_MAPPED EMPTY>
  <!ATTLIST BIT_MAPPED SOURCE_ADDRESS  CDATA  #REQUIRED>

<!ELEMENT REGISTER_VALUES (REGISTER_VALUE_RANGE*)>

<!ELEMENT REGISTER_VALUE_RANGE EMPTY>
  <!ATTLIST REGISTER_VALUE_RANGE REGISTER      CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE VALUE         CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE START_ADDRESS CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE LENGTH        CDATA #REQUIRED>

<!ELEMENT CODE (CODE_BLOCK*)>

<!ELEMENT CODE_BLOCK EMPTY>
  <!ATTLIST CODE_BLOCK  START  CDATA  #REQUIRED>
  <!ATTLIST CODE_BLOCK  END    CDATA  #REQUIRED>

<!ELEMENT DATA (DEFINED_DATA*)>

<!ELEMENT DEFINED_DATA (TYPEINFO_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST DEFINED_DATA ADDRESS             CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST DEFINED_DATA SIZE                CDATA  #IMPLIED>

<!ELEMENT EQUATES (EQUATE_GROUP*)>

<!ELEMENT EQUATE_GROUP (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, (EQUATE | BIT_MASK)*)>
  <!ATTLIST EQUATE_GROUP NAME       CDATA       #IMPLIED>
  <!ATTLIST EQUATE_GROUP BIT_FIELD  (yes | no)  #IMPLIED>

<!ELEMENT EQUATE (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST EQUATE NAME     CDATA  #REQUIRED>
  <!ATTLIST EQUATE VALUE    CDATA  #REQUIRED>
  <!ATTLIST EQUATE BIT_MASK CDATA  #IMPLIED>

<!ELEMENT BIT_MASK (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST BIT_MASK NAME   CDATA  #REQUIRED>
  <!ATTLIST BIT_MASK VALUE  CDATA  #REQUIRED>

<!ELEMENT COMMENTS (COMMENT*)>

<!ELEMENT COMMENT (#PCDATA)>
  <!ATTLIST COMMENT ADDRESS  CDATA                                            #REQUIRED>
  <!ATTLIST COMMENT TYPE     (end-of-line | repeatable | pre | post | plate)  #REQUIRED>

<!ELEMENT PROPERTIES (PROPERTY*)>

<!ELEMENT PROPERTY EMPTY>
  <!ATTLIST PROPERTY NAME     CDATA                                                #REQUIRED>
  <!ATTLIST PROPERTY ADDRESS  CDATA                                                #IMPLIED>
  <!ATTLIST PROPERTY TYPE     (string | long | int | double | void | bool | date)  #IMPLIED>
  <!ATTLIST PROPERTY VALUE    CDATA                                                #IMPLIED>

<!ELEMENT BOOKMARKS (BOOKMARK*)>

<!ELEMENT BOOKMARK EMPTY>
  <!ATTLIST BOOKMARK ADDRESS     CDATA  #REQUIRED>
  <!ATTLIST BOOKMARK TYPE        CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK CATEGORY    CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK DESCRIPTION CDATA  #IMPLIED>

<!ELEMENT PROGRAM_TREES (TREE*)>

<!ELEMENT TREE ((FOLDER | FRAGMENT)*)>
  <!ATTLIST TREE NAME CDATA #REQUIRED>

<!ELEMENT FOLDER ((FOLDER | FRAGMENT)*)>
  <!ATTLIST FOLDER NAME CDATA #REQUIRED>

<!ELEMENT FRAGMENT (ADDRESS_RANGE)*>
  <!ATTLIST FRAGMENT NAME CDATA #REQUIRED>

<!ELEMENT ADDRESS_RANGE EMPTY>
  <!ATTLIST ADDRESS_RANGE START  CDATA  #REQUIRED>
  <!ATTLIST ADDRESS_RANGE END    CDATA  #REQUIRED>

<!ELEMENT PROGRAM_ENTRY_POINTS (PROGRAM_ENTRY_POINT*)>

<!ELEMENT PROGRAM_ENTRY_POINT EMPTY>
  <!ATTLIST PROGRAM_ENTRY_POINT  ADDRESS  CDATA  #REQUIRED>

<!ELEMENT RELOCATION_TABLE (RELOCATION*)>

<!ELEMENT RELOCATION EMPTY>
  <!ATTLIST RELOCATION ADDRESS  CDATA  #REQUIRED>
  <!ATTLIST RELOCATION TYPE     CDATA  #REQUIRED>
  <!ATTLIST RELOCATION VALUE    CDATA  #REQUIRED>
  <!ATTLIST RELOCATION BYTES    CDATA  #IMPLIED>

<!ELEMENT SYMBOL_TABLE (SYMBOL*)>

<!ELEMENT SYMBOL EMPTY>
  <!ATTLIST SYMBOL ADDRESS   		CDATA            					 #REQUIRED>
  <!ATTLIST SYMBOL NAME      		CDATA             					 #REQUIRED>
  <!ATTLIST SYMBOL NAMESPACE 		CDATA             					 #IMPLIED>
  <!ATTLIST SYMBOL TYPE      		(global | local)  					 #IMPLIED>
  <!ATTLIST SYMBOL SOURCE_TYPE      (USER_DEFINED | IMPORTED | ANALYSIS) #IMPLIED>
  <!ATTLIST SYMBOL PRIMARY   		(y | n)           					 #IMPLIED>
  <!ATTLIST SYMBOL MANGLED   		CDATA             					 #IMPLIED>

<!ELEMENT FUNCTIONS (FUNCTION*)>

<!ELEMENT FUNCTION (RETURN_TYPE?, ADDRESS_RANGE*, REGULAR_CMT?, REPEATABLE_CMT?, TYPEINFO_CMT?, STACK_FRAME?, REGISTER_VAR*)>
  <!ATTLIST FUNCTION ENTRY_POINT       CDATA   #REQUIRED>
  <!ATTLIST FUNCTION NAME              CDATA   #IMPLIED>
  <!-- TODO: create xml attrs for each known attribute type -->
  <!ATTLIST FUNCTION LIBRARY_FUNCTION  (y | n) #IMPLIED>

<!ELEMENT RETURN_TYPE EMPTY>
  <!ATTLIST RETURN_TYPE DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST RETURN_TYPE DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST RETURN_TYPE SIZE                CDATA  #IMPLIED>

<!ELEMENT STACK_FRAME (STACK_VAR*)>
  <!ATTLIST STACK_FRAME LOCAL_VAR_SIZE         CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME PARAM_OFFSET           CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME REGISTER_SAVE_SIZE     CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME RETURN_ADDR_SIZE       CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME BYTES_PURGED           CDATA    #IMPLIED>

<!ELEMENT STACK_VAR (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST STACK_VAR STACK_PTR_OFFSET    CDATA  #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_VAR FRAME_PTR_OFFSET    CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR NAME                CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST STACK_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR SIZE                CDATA  #IMPLIED>

<!ELEMENT REGISTER_VAR (REGULAR_CMT?)>
  <!ATTLIST REGISTER_VAR NAME                CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR REGISTER            CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR DATATYPE            CDATA  #IMPLIED>
  <!ATTLIST REGISTER_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT MARKUP (MEMORY_REFERENCE      |
                  STACK_REFERENCE       |
                  EXT_LIBRARY_REFERENCE |
                  EQUATE_REFERENCE      |
                  MANUAL_OPERAND        |
                  MANUAL_INSTRUCTION)*>

<!-- An OPERAND_INDEX is omitted for a mnemonic reference    -->
<!-- The first operand is identified with OPERAND_INDEX=0 -->
<!ELEMENT MEMORY_REFERENCE EMPTY>
  <!ATTLIST MEMORY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE TO_ADDRESS     CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE BASE_ADDRESS   CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE PRIMARY        (y | n)  #IMPLIED>

<!ELEMENT STACK_REFERENCE EMPTY>
  <!ATTLIST STACK_REFERENCE ADDRESS          CDATA    #REQUIRED>
  <!ATTLIST STACK_REFERENCE OPERAND_INDEX    CDATA    #IMPLIED>
  <!ATTLIST STACK_REFERENCE USER_DEFINED     (y | n)  #IMPLIED>
  <!ATTLIST STACK_REFERENCE STACK_PTR_OFFSET CDATA    #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_REFERENCE FRAME_PTR_OFFSET CDATA    #IMPLIED>

<!ELEMENT EXT_LIBRARY_REFERENCE EMPTY>
  <!ATTLIST EXT_LIBRARY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_PROG_NAME  CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_LABEL      CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ORDINAL    CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ADDR       CDATA    #IMPLIED>

<!ELEMENT EQUATE_REFERENCE EMPTY>
  <!ATTLIST EQUATE_REFERENCE ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE OPERAND_INDEX  CDATA  #IMPLIED>
  <!ATTLIST EQUATE_REFERENCE NAME           CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE VALUE          CDATA  #IMPLIED>

<!ELEMENT MANUAL_OPERAND (#PCDATA)>
  <!ATTLIST MANUAL_OPERAND ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST MANUAL_OPERAND OPERAND_INDEX  CDATA  #REQUIRED>

<!ELEMENT MANUAL_INSTRUCTION (#PCDATA)>
  <!ATTLIST MANUAL_INSTRUCTION ADDRESS CDATA #REQUIRED>

<!ELEMENT EXT_LIBRARY_TABLE (EXT_LIBRARY*)>

<!ELEMENT EXT_LIBRARY EMPTY>
  <!ATTLIST EXT_LIBRARY NAME  CDATA  #REQUIRED>
  <!ATTLIST EXT_LIBRARY PATH  CDATA  #IMPLIED>

<!-- ************************************************************* -->
<!--                                                               -->
<!--                Data DTD                                       -->
<!--                                                               -->
<!-- ************************************************************* -->

<!ELEMENT DATATYPES (STRUCTURE | UNION | FUNCTION_DEF | ENUM | TYPE_DEF)*>

<!ELEMENT MEMBER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST MEMBER OFFSET              CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST MEMBER NAME                CDATA  #IMPLIED>
  <!ATTLIST MEMBER SIZE                CDATA  #IMPLIED>

<!ELEMENT STRUCTURE (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST STRUCTURE NAME             CDATA   #REQUIRED>
  <!ATTLIST STRUCTURE NAMESPACE        CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE SIZE             CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE VARIABLE_LENGTH  (y | n) #IMPLIED>

<!ELEMENT UNION (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST UNION NAME       CDATA  #REQUIRED>
  <!ATTLIST UNION NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST UNION SIZE       CDATA  #IMPLIED>

<!ELEMENT FUNCTION_DEF (REGULAR_CMT?, REPEATABLE_CMT?, RETURN_TYPE?, PARAMETER*)>
  <!ATTLIST FUNCTION_DEF NAME       CDATA  #REQUIRED>
  <!ATTLIST FUNCTION_DEF NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT PARAMETER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST PARAMETER ORDINAL             CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST PARAMETER NAME                CDATA  #IMPLIED>
  <!ATTLIST PARAMETER SIZE                CDATA  #IMPLIED>

<!ELEMENT TYPE_DEF (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST TYPE_DEF NAME                CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF NAMESPACE           CDATA #IMPLIED>
  <!ATTLIST TYPE_DEF DATATYPE            CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF DATATYPE_NAMESPACE  CDATA #IMPLIED>

<!ELEMENT ENUM (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, ENUM_ENTRY*)>
  <!ATTLIST ENUM NAME       CDATA  #REQUIRED>
  <!ATTLIST ENUM NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST ENUM SIZE       CDATA  #IMPLIED>

<!ELEMENT ENUM_ENTRY (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST ENUM_ENTRY NAME   CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY VALUE  CDATA  #REQUIRED>

]>
<PROGRAM NAME="heartbleeder" EXE_PATH="/home/fouque/T&#xE9;l&#xE9;chargements/heartbleeder" EXE_FORMAT="Executable and Linking Format (ELF)" IMAGE_BASE="08048000">
    <INFO_SOURCE USER="fouque" TOOL="Ghidra 9.1.2" TIMESTAMP="Fri Jul 10 15:33:03 CEST 2020" />
    <PROCESSOR NAME="x86" LANGUAGE_PROVIDER="x86:LE:32:default:gcc" ENDIAN="little" />
    <DATATYPES>
        <STRUCTURE NAME="Elf32_Ehdr" NAMESPACE="/ELF" SIZE="0x34">
            <MEMBER OFFSET="0x0" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="e_ident_magic_num" SIZE="0x1" />
            <MEMBER OFFSET="0x1" DATATYPE="string" DATATYPE_NAMESPACE="/" NAME="e_ident_magic_str" SIZE="0x3" />
            <MEMBER OFFSET="0x4" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="e_ident_class" SIZE="0x1" />
            <MEMBER OFFSET="0x5" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="e_ident_data" SIZE="0x1" />
            <MEMBER OFFSET="0x6" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="e_ident_version" SIZE="0x1" />
            <MEMBER OFFSET="0x7" DATATYPE="byte[9]" DATATYPE_NAMESPACE="/" NAME="e_ident_pad" SIZE="0x9" />
            <MEMBER OFFSET="0x10" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_type" SIZE="0x2" />
            <MEMBER OFFSET="0x12" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_machine" SIZE="0x2" />
            <MEMBER OFFSET="0x14" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="e_version" SIZE="0x4" />
            <MEMBER OFFSET="0x18" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="e_entry" SIZE="0x4" />
            <MEMBER OFFSET="0x1c" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="e_phoff" SIZE="0x4" />
            <MEMBER OFFSET="0x20" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="e_shoff" SIZE="0x4" />
            <MEMBER OFFSET="0x24" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="e_flags" SIZE="0x4" />
            <MEMBER OFFSET="0x28" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_ehsize" SIZE="0x2" />
            <MEMBER OFFSET="0x2a" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_phentsize" SIZE="0x2" />
            <MEMBER OFFSET="0x2c" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_phnum" SIZE="0x2" />
            <MEMBER OFFSET="0x2e" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_shentsize" SIZE="0x2" />
            <MEMBER OFFSET="0x30" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_shnum" SIZE="0x2" />
            <MEMBER OFFSET="0x32" DATATYPE="word" DATATYPE_NAMESPACE="/" NAME="e_shstrndx" SIZE="0x2" />
        </STRUCTURE>
        <STRUCTURE NAME="Elf32_Phdr" NAMESPACE="/ELF" SIZE="0x20">
            <MEMBER OFFSET="0x0" DATATYPE="Elf_ProgramHeaderType_x86" DATATYPE_NAMESPACE="/ELF" NAME="p_type" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="p_offset" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="p_vaddr" SIZE="0x4" />
            <MEMBER OFFSET="0xc" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="p_paddr" SIZE="0x4" />
            <MEMBER OFFSET="0x10" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="p_filesz" SIZE="0x4" />
            <MEMBER OFFSET="0x14" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="p_memsz" SIZE="0x4" />
            <MEMBER OFFSET="0x18" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="p_flags" SIZE="0x4" />
            <MEMBER OFFSET="0x1c" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="p_align" SIZE="0x4" />
        </STRUCTURE>
        <STRUCTURE NAME="Elf32_Shdr" NAMESPACE="/ELF" SIZE="0x28">
            <MEMBER OFFSET="0x0" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sh_name" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="Elf_SectionHeaderType_x86" DATATYPE_NAMESPACE="/ELF" NAME="sh_type" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sh_flags" SIZE="0x4" />
            <MEMBER OFFSET="0xc" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sh_addr" SIZE="0x4" />
            <MEMBER OFFSET="0x10" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sh_offset" SIZE="0x4" />
            <MEMBER OFFSET="0x14" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sh_size" SIZE="0x4" />
            <MEMBER OFFSET="0x18" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sh_link" SIZE="0x4" />
            <MEMBER OFFSET="0x1c" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sh_info" SIZE="0x4" />
            <MEMBER OFFSET="0x20" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sh_addralign" SIZE="0x4" />
            <MEMBER OFFSET="0x24" DATATYPE="dword" DATATYPE_NAMESPACE="/" NAME="sh_entsize" SIZE="0x4" />
        </STRUCTURE>
        <ENUM NAME="Elf_ProgramHeaderType_x86" NAMESPACE="/ELF" SIZE="0x4">
            <ENUM_ENTRY NAME="PT_DYNAMIC" VALUE="0x2" />
            <ENUM_ENTRY NAME="PT_GNU_EH_FRAME" VALUE="0x6474e550" />
            <ENUM_ENTRY NAME="PT_GNU_RELRO" VALUE="0x6474e552" />
            <ENUM_ENTRY NAME="PT_GNU_STACK" VALUE="0x6474e551" />
            <ENUM_ENTRY NAME="PT_INTERP" VALUE="0x3" />
            <ENUM_ENTRY NAME="PT_LOAD" VALUE="0x1" />
            <ENUM_ENTRY NAME="PT_NOTE" VALUE="0x4" />
            <ENUM_ENTRY NAME="PT_NULL" VALUE="0x0" />
            <ENUM_ENTRY NAME="PT_PHDR" VALUE="0x6" />
            <ENUM_ENTRY NAME="PT_SHLIB" VALUE="0x5" />
            <ENUM_ENTRY NAME="PT_TLS" VALUE="0x7" />
        </ENUM>
        <ENUM NAME="Elf_SectionHeaderType_x86" NAMESPACE="/ELF" SIZE="0x4">
            <ENUM_ENTRY NAME="SHT_CHECKSUM" VALUE="0x6ffffff8" />
            <ENUM_ENTRY NAME="SHT_DYNAMIC" VALUE="0x6" />
            <ENUM_ENTRY NAME="SHT_DYNSYM" VALUE="0xb" />
            <ENUM_ENTRY NAME="SHT_FINI_ARRAY" VALUE="0xf" />
            <ENUM_ENTRY NAME="SHT_GNU_ATTRIBUTES" VALUE="0x6ffffff5" />
            <ENUM_ENTRY NAME="SHT_GNU_HASH" VALUE="0x6ffffff6" />
            <ENUM_ENTRY NAME="SHT_GNU_LIBLIST" VALUE="0x6ffffff7" />
            <ENUM_ENTRY NAME="SHT_GNU_verdef" VALUE="0x6ffffffd" />
            <ENUM_ENTRY NAME="SHT_GNU_verneed" VALUE="0x6ffffffe" />
            <ENUM_ENTRY NAME="SHT_GNU_versym" VALUE="0x6fffffff" />
            <ENUM_ENTRY NAME="SHT_GROUP" VALUE="0x11" />
            <ENUM_ENTRY NAME="SHT_HASH" VALUE="0x5" />
            <ENUM_ENTRY NAME="SHT_INIT_ARRAY" VALUE="0xe" />
            <ENUM_ENTRY NAME="SHT_NOBITS" VALUE="0x8" />
            <ENUM_ENTRY NAME="SHT_NOTE" VALUE="0x7" />
            <ENUM_ENTRY NAME="SHT_NULL" VALUE="0x0" />
            <ENUM_ENTRY NAME="SHT_PREINIT_ARRAY" VALUE="0x10" />
            <ENUM_ENTRY NAME="SHT_PROGBITS" VALUE="0x1" />
            <ENUM_ENTRY NAME="SHT_REL" VALUE="0x9" />
            <ENUM_ENTRY NAME="SHT_RELA" VALUE="0x4" />
            <ENUM_ENTRY NAME="SHT_SHLIB" VALUE="0xa" />
            <ENUM_ENTRY NAME="SHT_STRTAB" VALUE="0x3" />
            <ENUM_ENTRY NAME="SHT_SUNW_COMDAT" VALUE="0x6ffffffb" />
            <ENUM_ENTRY NAME="SHT_SUNW_move" VALUE="0x6ffffffa" />
            <ENUM_ENTRY NAME="SHT_SUNW_syminfo" VALUE="0x6ffffffc" />
            <ENUM_ENTRY NAME="SHT_SYMTAB" VALUE="0x2" />
            <ENUM_ENTRY NAME="SHT_SYMTAB_SHNDX" VALUE="0x12" />
        </ENUM>
    </DATATYPES>
    <MEMORY_MAP>
        <MEMORY_SECTION NAME="segment_1.1" START_ADDR="08048000" LENGTH="0xc00" PERMISSIONS="r" COMMENT="Loadable segment  [0x8048000 - 0x8249c1f] (disabled execute bit)">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_linux.bytes" FILE_OFFSET="0x0" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME=".text" START_ADDR="08048c00" LENGTH="0x201020" PERMISSIONS="rx" COMMENT="SHT_PROGBITS  [0x8048c00 - 0x8249c1f]">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_linux.bytes" FILE_OFFSET="0xc00" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME=".rodata" START_ADDR="0824a000" LENGTH="0x1359f8" PERMISSIONS="r" COMMENT="SHT_PROGBITS  [0x824a000 - 0x837f9f7]">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_linux.bytes" FILE_OFFSET="0x201c20" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME=".typelink" START_ADDR="0837f9f8" LENGTH="0x9e4" PERMISSIONS="r" COMMENT="SHT_PROGBITS  [0x837f9f8 - 0x83803db]">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_linux.bytes" FILE_OFFSET="0x337ffc" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME=".gopclntab" START_ADDR="083803e0" LENGTH="0xba7c5" PERMISSIONS="r" COMMENT="SHT_PROGBITS  [0x83803e0 - 0x843aba4]">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_linux.bytes" FILE_OFFSET="0x3389e0" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME=".noptrdata" START_ADDR="0843b000" LENGTH="0x1546c" PERMISSIONS="rw" COMMENT="SHT_PROGBITS  [0x843b000 - 0x845046b]">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_linux.bytes" FILE_OFFSET="0x3f31a5" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME=".data" START_ADDR="08450480" LENGTH="0x5834" PERMISSIONS="rw" COMMENT="SHT_PROGBITS  [0x8450480 - 0x8455cb3]">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_linux.bytes" FILE_OFFSET="0x408611" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME=".bss" START_ADDR="08455cc0" LENGTH="0x69e0" PERMISSIONS="rw" COMMENT="SHT_NOBITS  [0x8455cc0 - 0x845c69f]" />
        <MEMORY_SECTION NAME=".noptrbss" START_ADDR="0845c6a0" LENGTH="0xdfa0" PERMISSIONS="rw" COMMENT="SHT_NOBITS  [0x845c6a0 - 0x846a63f]" />
        <MEMORY_SECTION NAME=".shstrtab" START_ADDR=".shstrtab::OTHER:00000000" LENGTH="0x58" PERMISSIONS="r" COMMENT="SHT_STRTAB [not-loaded]">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_linux.bytes" FILE_OFFSET="0x40de45" />
        </MEMORY_SECTION>
        <MEMORY_SECTION NAME="_elfSectionHeaders" START_ADDR="_elfSectionHeaders::OTHER:00000000" LENGTH="0x1b8" PERMISSIONS="r" COMMENT="Elf Section Headers">
            <MEMORY_CONTENTS FILE_NAME="heartbleeder_linux.bytes" FILE_OFFSET="0x40de9d" />
        </MEMORY_SECTION>
    </MEMORY_MAP>
    <REGISTER_VALUES />
    <CODE />
    <DATA>
        <DEFINED_DATA ADDRESS="08048000" DATATYPE="Elf32_Ehdr" DATATYPE_NAMESPACE="/ELF" SIZE="0x34" />
        <DEFINED_DATA ADDRESS="08048034" DATATYPE="Elf32_Phdr[6]" DATATYPE_NAMESPACE="/ELF" SIZE="0xc0" />
        <DEFINED_DATA ADDRESS=".shstrtab::OTHER:00000001" DATATYPE="TerminatedCString" DATATYPE_NAMESPACE="/" SIZE="0xa" />
        <DEFINED_DATA ADDRESS=".shstrtab::OTHER:0000000b" DATATYPE="TerminatedCString" DATATYPE_NAMESPACE="/" SIZE="0x6" />
        <DEFINED_DATA ADDRESS=".shstrtab::OTHER:00000011" DATATYPE="TerminatedCString" DATATYPE_NAMESPACE="/" SIZE="0x8" />
        <DEFINED_DATA ADDRESS=".shstrtab::OTHER:00000019" DATATYPE="TerminatedCString" DATATYPE_NAMESPACE="/" SIZE="0xa" />
        <DEFINED_DATA ADDRESS=".shstrtab::OTHER:00000023" DATATYPE="TerminatedCString" DATATYPE_NAMESPACE="/" SIZE="0xa" />
        <DEFINED_DATA ADDRESS=".shstrtab::OTHER:0000002d" DATATYPE="TerminatedCString" DATATYPE_NAMESPACE="/" SIZE="0xb" />
        <DEFINED_DATA ADDRESS=".shstrtab::OTHER:00000038" DATATYPE="TerminatedCString" DATATYPE_NAMESPACE="/" SIZE="0xb" />
        <DEFINED_DATA ADDRESS=".shstrtab::OTHER:00000043" DATATYPE="TerminatedCString" DATATYPE_NAMESPACE="/" SIZE="0x6" />
        <DEFINED_DATA ADDRESS=".shstrtab::OTHER:00000049" DATATYPE="TerminatedCString" DATATYPE_NAMESPACE="/" SIZE="0x5" />
        <DEFINED_DATA ADDRESS=".shstrtab::OTHER:0000004e" DATATYPE="TerminatedCString" DATATYPE_NAMESPACE="/" SIZE="0xa" />
        <DEFINED_DATA ADDRESS="_elfSectionHeaders::OTHER:00000000" DATATYPE="Elf32_Shdr[11]" DATATYPE_NAMESPACE="/ELF" SIZE="0x1b8" />
    </DATA>
    <EQUATES>
        <EQUATE_GROUP />
    </EQUATES>
    <COMMENTS>
        <COMMENT ADDRESS="08048034" TYPE="end-of-line">PT_PHDR - Program header table</COMMENT>
        <COMMENT ADDRESS="_elfSectionHeaders::OTHER:00000000" TYPE="end-of-line">SECTION0 - SHT_NULL</COMMENT>
    </COMMENTS>
    <PROPERTIES>
        <PROPERTY NAME="Program Information.Created With Ghidra Version" TYPE="string" VALUE="9.1.2" />
        <PROPERTY NAME="Program Information.Date Created" TYPE="date" VALUE="0x17338e881a5" />
        <PROPERTY NAME="Program Information.ELF File Type" TYPE="string" VALUE="executable" />
        <PROPERTY NAME="Program Information.ELF Original Image Base" TYPE="string" VALUE="0x8048000" />
        <PROPERTY NAME="Program Information.ELF Prelinked" TYPE="bool" VALUE="n" />
        <PROPERTY NAME="Program Information.Executable Format" TYPE="string" VALUE="Executable and Linking Format (ELF)" />
        <PROPERTY NAME="Program Information.Executable Location" TYPE="string" VALUE="/home/fouque/T&#xE9;l&#xE9;chargements/heartbleeder" />
        <PROPERTY NAME="Program Information.Executable MD5" TYPE="string" VALUE="29fae7c1b515c1031edf1844c3216d12" />
        <PROPERTY NAME="Program Information.Executable SHA256" TYPE="string" VALUE="842c8ba713ce89e70ef2b80ba364cff6ad233aacbe7aab2d0b11384500383706" />
        <PROPERTY NAME="Program Information.FSRL" TYPE="string" VALUE="file:///home/fouque/T%C3%A9l%C3%A9chargements/heartbleeder?MD5=29fae7c1b515c1031edf1844c3216d12" />
        <PROPERTY NAME="Program Information.Relocatable" TYPE="bool" VALUE="n" />
    </PROPERTIES>
    <BOOKMARKS />
    <PROGRAM_TREES>
        <TREE NAME="Program Tree">
            <FRAGMENT NAME=".noptrbss">
                <ADDRESS_RANGE START="0845c6a0" END="0846a63f" />
            </FRAGMENT>
            <FRAGMENT NAME=".bss">
                <ADDRESS_RANGE START="08455cc0" END="0845c69f" />
            </FRAGMENT>
            <FRAGMENT NAME=".data">
                <ADDRESS_RANGE START="08450480" END="08455cb3" />
            </FRAGMENT>
            <FRAGMENT NAME=".noptrdata">
                <ADDRESS_RANGE START="0843b000" END="0845046b" />
            </FRAGMENT>
            <FRAGMENT NAME=".gopclntab">
                <ADDRESS_RANGE START="083803e0" END="0843aba4" />
            </FRAGMENT>
            <FRAGMENT NAME=".typelink">
                <ADDRESS_RANGE START="0837f9f8" END="083803db" />
            </FRAGMENT>
            <FRAGMENT NAME=".rodata">
                <ADDRESS_RANGE START="0824a000" END="0837f9f7" />
            </FRAGMENT>
            <FRAGMENT NAME=".text">
                <ADDRESS_RANGE START="08048c00" END="08249c1f" />
            </FRAGMENT>
            <FRAGMENT NAME="segment_1.1">
                <ADDRESS_RANGE START="08048000" END="08048bff" />
            </FRAGMENT>
            <FRAGMENT NAME=".shstrtab">
                <ADDRESS_RANGE START=".shstrtab::OTHER:00000000" END=".shstrtab::OTHER:00000057" />
            </FRAGMENT>
            <FRAGMENT NAME="_elfSectionHeaders">
                <ADDRESS_RANGE START="_elfSectionHeaders::OTHER:00000000" END="_elfSectionHeaders::OTHER:000001b7" />
            </FRAGMENT>
        </TREE>
    </PROGRAM_TREES>
    <PROGRAM_ENTRY_POINTS>
        <PROGRAM_ENTRY_POINT ADDRESS="0807e9e0" />
    </PROGRAM_ENTRY_POINTS>
    <RELOCATION_TABLE />
    <SYMBOL_TABLE>
        <SYMBOL ADDRESS="0807e9e0" NAME="entry" NAMESPACE="" TYPE="global" SOURCE_TYPE="IMPORTED" PRIMARY="y" />
    </SYMBOL_TABLE>
    <FUNCTIONS>
        <FUNCTION ENTRY_POINT="0807e9e0" NAME="entry" LIBRARY_FUNCTION="n">
            <ADDRESS_RANGE START="0807e9e0" END="0807e9e0" />
            <STACK_FRAME LOCAL_VAR_SIZE="0x4" PARAM_OFFSET="0x4" RETURN_ADDR_SIZE="0x0" />
        </FUNCTION>
    </FUNCTIONS>
    <MARKUP />
    <EXT_LIBRARY_TABLE />
</PROGRAM>
